apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ze8140ugp-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ze8140ugp-java-springboot 
  name: ze8140ugp-java-springboot
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ze8140ugp-java-springboot 
